// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1
// 	protoc        v3.11.3
// source: OakShared.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Vec3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y *float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	Z *float32 `protobuf:"fixed32,3,opt,name=z" json:"z,omitempty"`
}

func (x *Vec3) Reset() {
	*x = Vec3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OakShared_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vec3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec3) ProtoMessage() {}

func (x *Vec3) ProtoReflect() protoreflect.Message {
	mi := &file_OakShared_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec3.ProtoReflect.Descriptor instead.
func (*Vec3) Descriptor() ([]byte, []int) {
	return file_OakShared_proto_rawDescGZIP(), []int{0}
}

func (x *Vec3) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Vec3) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Vec3) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

type GameStatSaveGameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatValue *int32  `protobuf:"varint,1,opt,name=stat_value,json=statValue" json:"stat_value,omitempty"`
	StatPath  *string `protobuf:"bytes,2,opt,name=stat_path,json=statPath" json:"stat_path,omitempty"`
}

func (x *GameStatSaveGameData) Reset() {
	*x = GameStatSaveGameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OakShared_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStatSaveGameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatSaveGameData) ProtoMessage() {}

func (x *GameStatSaveGameData) ProtoReflect() protoreflect.Message {
	mi := &file_OakShared_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatSaveGameData.ProtoReflect.Descriptor instead.
func (*GameStatSaveGameData) Descriptor() ([]byte, []int) {
	return file_OakShared_proto_rawDescGZIP(), []int{1}
}

func (x *GameStatSaveGameData) GetStatValue() int32 {
	if x != nil && x.StatValue != nil {
		return *x.StatValue
	}
	return 0
}

func (x *GameStatSaveGameData) GetStatPath() string {
	if x != nil && x.StatPath != nil {
		return *x.StatPath
	}
	return ""
}

type InventoryCategorySaveData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseCategoryDefinitionHash *uint32 `protobuf:"varint,1,opt,name=base_category_definition_hash,json=baseCategoryDefinitionHash" json:"base_category_definition_hash,omitempty"`
	Quantity                   *int32  `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
}

func (x *InventoryCategorySaveData) Reset() {
	*x = InventoryCategorySaveData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OakShared_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InventoryCategorySaveData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryCategorySaveData) ProtoMessage() {}

func (x *InventoryCategorySaveData) ProtoReflect() protoreflect.Message {
	mi := &file_OakShared_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryCategorySaveData.ProtoReflect.Descriptor instead.
func (*InventoryCategorySaveData) Descriptor() ([]byte, []int) {
	return file_OakShared_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryCategorySaveData) GetBaseCategoryDefinitionHash() uint32 {
	if x != nil && x.BaseCategoryDefinitionHash != nil {
		return *x.BaseCategoryDefinitionHash
	}
	return 0
}

func (x *InventoryCategorySaveData) GetQuantity() int32 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

type OakSDUSaveGameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SduLevel    *int32  `protobuf:"varint,1,opt,name=sdu_level,json=sduLevel" json:"sdu_level,omitempty"`
	SduDataPath *string `protobuf:"bytes,2,opt,name=sdu_data_path,json=sduDataPath" json:"sdu_data_path,omitempty"`
}

func (x *OakSDUSaveGameData) Reset() {
	*x = OakSDUSaveGameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OakShared_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OakSDUSaveGameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OakSDUSaveGameData) ProtoMessage() {}

func (x *OakSDUSaveGameData) ProtoReflect() protoreflect.Message {
	mi := &file_OakShared_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OakSDUSaveGameData.ProtoReflect.Descriptor instead.
func (*OakSDUSaveGameData) Descriptor() ([]byte, []int) {
	return file_OakShared_proto_rawDescGZIP(), []int{3}
}

func (x *OakSDUSaveGameData) GetSduLevel() int32 {
	if x != nil && x.SduLevel != nil {
		return *x.SduLevel
	}
	return 0
}

func (x *OakSDUSaveGameData) GetSduDataPath() string {
	if x != nil && x.SduDataPath != nil {
		return *x.SduDataPath
	}
	return ""
}

type RegisteredDownloadableEntitlement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         *int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Consumed   *uint32 `protobuf:"varint,2,opt,name=consumed" json:"consumed,omitempty"`
	Registered *bool   `protobuf:"varint,3,opt,name=registered" json:"registered,omitempty"`
	Seen       *bool   `protobuf:"varint,4,opt,name=seen" json:"seen,omitempty"`
}

func (x *RegisteredDownloadableEntitlement) Reset() {
	*x = RegisteredDownloadableEntitlement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OakShared_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisteredDownloadableEntitlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredDownloadableEntitlement) ProtoMessage() {}

func (x *RegisteredDownloadableEntitlement) ProtoReflect() protoreflect.Message {
	mi := &file_OakShared_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredDownloadableEntitlement.ProtoReflect.Descriptor instead.
func (*RegisteredDownloadableEntitlement) Descriptor() ([]byte, []int) {
	return file_OakShared_proto_rawDescGZIP(), []int{4}
}

func (x *RegisteredDownloadableEntitlement) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *RegisteredDownloadableEntitlement) GetConsumed() uint32 {
	if x != nil && x.Consumed != nil {
		return *x.Consumed
	}
	return 0
}

func (x *RegisteredDownloadableEntitlement) GetRegistered() bool {
	if x != nil && x.Registered != nil {
		return *x.Registered
	}
	return false
}

func (x *RegisteredDownloadableEntitlement) GetSeen() bool {
	if x != nil && x.Seen != nil {
		return *x.Seen
	}
	return false
}

type RegisteredDownloadableEntitlements struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntitlementSourceAssetPath *string                              `protobuf:"bytes,1,opt,name=entitlement_source_asset_path,json=entitlementSourceAssetPath" json:"entitlement_source_asset_path,omitempty"`
	EntitlementIds             []int64                              `protobuf:"varint,2,rep,name=entitlement_ids,json=entitlementIds" json:"entitlement_ids,omitempty"`
	Entitlements               []*RegisteredDownloadableEntitlement `protobuf:"bytes,3,rep,name=entitlements" json:"entitlements,omitempty"`
}

func (x *RegisteredDownloadableEntitlements) Reset() {
	*x = RegisteredDownloadableEntitlements{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OakShared_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisteredDownloadableEntitlements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredDownloadableEntitlements) ProtoMessage() {}

func (x *RegisteredDownloadableEntitlements) ProtoReflect() protoreflect.Message {
	mi := &file_OakShared_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredDownloadableEntitlements.ProtoReflect.Descriptor instead.
func (*RegisteredDownloadableEntitlements) Descriptor() ([]byte, []int) {
	return file_OakShared_proto_rawDescGZIP(), []int{5}
}

func (x *RegisteredDownloadableEntitlements) GetEntitlementSourceAssetPath() string {
	if x != nil && x.EntitlementSourceAssetPath != nil {
		return *x.EntitlementSourceAssetPath
	}
	return ""
}

func (x *RegisteredDownloadableEntitlements) GetEntitlementIds() []int64 {
	if x != nil {
		return x.EntitlementIds
	}
	return nil
}

func (x *RegisteredDownloadableEntitlements) GetEntitlements() []*RegisteredDownloadableEntitlement {
	if x != nil {
		return x.Entitlements
	}
	return nil
}

var File_OakShared_proto protoreflect.FileDescriptor

var file_OakShared_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x4f, 0x61, 0x6b, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x4f, 0x61, 0x6b, 0x53, 0x61, 0x76, 0x65, 0x22, 0x30, 0x0a, 0x04, 0x56, 0x65,
	0x63, 0x33, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c,
	0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x52, 0x0a, 0x14,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x53, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x50, 0x61, 0x74, 0x68,
	0x22, 0x7a, 0x0a, 0x19, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x53, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x41, 0x0a,
	0x1d, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x1a, 0x62, 0x61, 0x73, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x55, 0x0a, 0x12,
	0x4f, 0x61, 0x6b, 0x53, 0x44, 0x55, 0x53, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x64, 0x75, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x64, 0x75, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x22, 0x0a, 0x0d, 0x73, 0x64, 0x75, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x64, 0x75, 0x44, 0x61, 0x74, 0x61, 0x50,
	0x61, 0x74, 0x68, 0x22, 0x83, 0x01, 0x0a, 0x21, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x65, 0x64, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x65, 0x65, 0x6e, 0x22, 0xe0, 0x01, 0x0a, 0x22, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x41, 0x0a, 0x1d, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x1a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0e, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x12, 0x4e, 0x0a, 0x0c,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x4f, 0x61, 0x6b, 0x53, 0x61, 0x76, 0x65, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x61,
	0x62, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0c,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x29, 0x5a, 0x27,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x66, 0x69, 0x32, 0x30,
	0x31, 0x37, 0x2f, 0x62, 0x6c, 0x33, 0x2d, 0x73, 0x61, 0x76, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62,
}

var (
	file_OakShared_proto_rawDescOnce sync.Once
	file_OakShared_proto_rawDescData = file_OakShared_proto_rawDesc
)

func file_OakShared_proto_rawDescGZIP() []byte {
	file_OakShared_proto_rawDescOnce.Do(func() {
		file_OakShared_proto_rawDescData = protoimpl.X.CompressGZIP(file_OakShared_proto_rawDescData)
	})
	return file_OakShared_proto_rawDescData
}

var file_OakShared_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_OakShared_proto_goTypes = []interface{}{
	(*Vec3)(nil),                               // 0: OakSave.Vec3
	(*GameStatSaveGameData)(nil),               // 1: OakSave.GameStatSaveGameData
	(*InventoryCategorySaveData)(nil),          // 2: OakSave.InventoryCategorySaveData
	(*OakSDUSaveGameData)(nil),                 // 3: OakSave.OakSDUSaveGameData
	(*RegisteredDownloadableEntitlement)(nil),  // 4: OakSave.RegisteredDownloadableEntitlement
	(*RegisteredDownloadableEntitlements)(nil), // 5: OakSave.RegisteredDownloadableEntitlements
}
var file_OakShared_proto_depIdxs = []int32{
	4, // 0: OakSave.RegisteredDownloadableEntitlements.entitlements:type_name -> OakSave.RegisteredDownloadableEntitlement
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_OakShared_proto_init() }
func file_OakShared_proto_init() {
	if File_OakShared_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_OakShared_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vec3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OakShared_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStatSaveGameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OakShared_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InventoryCategorySaveData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OakShared_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OakSDUSaveGameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OakShared_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisteredDownloadableEntitlement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OakShared_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisteredDownloadableEntitlements); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_OakShared_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OakShared_proto_goTypes,
		DependencyIndexes: file_OakShared_proto_depIdxs,
		MessageInfos:      file_OakShared_proto_msgTypes,
	}.Build()
	File_OakShared_proto = out.File
	file_OakShared_proto_rawDesc = nil
	file_OakShared_proto_goTypes = nil
	file_OakShared_proto_depIdxs = nil
}
