// Code generated by protoc-gen-go. DO NOT EDIT.
// source: OakShared.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vec3 struct {
	X                    *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	Z                    *float32 `protobuf:"fixed32,3,opt,name=z" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vec3) Reset()         { *m = Vec3{} }
func (m *Vec3) String() string { return proto.CompactTextString(m) }
func (*Vec3) ProtoMessage()    {}
func (*Vec3) Descriptor() ([]byte, []int) {
	return fileDescriptor_24942b0aee0bf7ae, []int{0}
}

func (m *Vec3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vec3.Unmarshal(m, b)
}
func (m *Vec3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vec3.Marshal(b, m, deterministic)
}
func (m *Vec3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vec3.Merge(m, src)
}
func (m *Vec3) XXX_Size() int {
	return xxx_messageInfo_Vec3.Size(m)
}
func (m *Vec3) XXX_DiscardUnknown() {
	xxx_messageInfo_Vec3.DiscardUnknown(m)
}

var xxx_messageInfo_Vec3 proto.InternalMessageInfo

func (m *Vec3) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Vec3) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Vec3) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

type GameStatSaveGameData struct {
	StatValue            *int32   `protobuf:"varint,1,opt,name=stat_value,json=statValue" json:"stat_value,omitempty"`
	StatPath             *string  `protobuf:"bytes,2,opt,name=stat_path,json=statPath" json:"stat_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameStatSaveGameData) Reset()         { *m = GameStatSaveGameData{} }
func (m *GameStatSaveGameData) String() string { return proto.CompactTextString(m) }
func (*GameStatSaveGameData) ProtoMessage()    {}
func (*GameStatSaveGameData) Descriptor() ([]byte, []int) {
	return fileDescriptor_24942b0aee0bf7ae, []int{1}
}

func (m *GameStatSaveGameData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameStatSaveGameData.Unmarshal(m, b)
}
func (m *GameStatSaveGameData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameStatSaveGameData.Marshal(b, m, deterministic)
}
func (m *GameStatSaveGameData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameStatSaveGameData.Merge(m, src)
}
func (m *GameStatSaveGameData) XXX_Size() int {
	return xxx_messageInfo_GameStatSaveGameData.Size(m)
}
func (m *GameStatSaveGameData) XXX_DiscardUnknown() {
	xxx_messageInfo_GameStatSaveGameData.DiscardUnknown(m)
}

var xxx_messageInfo_GameStatSaveGameData proto.InternalMessageInfo

func (m *GameStatSaveGameData) GetStatValue() int32 {
	if m != nil && m.StatValue != nil {
		return *m.StatValue
	}
	return 0
}

func (m *GameStatSaveGameData) GetStatPath() string {
	if m != nil && m.StatPath != nil {
		return *m.StatPath
	}
	return ""
}

type InventoryCategorySaveData struct {
	BaseCategoryDefinitionHash *uint32  `protobuf:"varint,1,opt,name=base_category_definition_hash,json=baseCategoryDefinitionHash" json:"base_category_definition_hash,omitempty"`
	Quantity                   *int32   `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *InventoryCategorySaveData) Reset()         { *m = InventoryCategorySaveData{} }
func (m *InventoryCategorySaveData) String() string { return proto.CompactTextString(m) }
func (*InventoryCategorySaveData) ProtoMessage()    {}
func (*InventoryCategorySaveData) Descriptor() ([]byte, []int) {
	return fileDescriptor_24942b0aee0bf7ae, []int{2}
}

func (m *InventoryCategorySaveData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryCategorySaveData.Unmarshal(m, b)
}
func (m *InventoryCategorySaveData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryCategorySaveData.Marshal(b, m, deterministic)
}
func (m *InventoryCategorySaveData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryCategorySaveData.Merge(m, src)
}
func (m *InventoryCategorySaveData) XXX_Size() int {
	return xxx_messageInfo_InventoryCategorySaveData.Size(m)
}
func (m *InventoryCategorySaveData) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryCategorySaveData.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryCategorySaveData proto.InternalMessageInfo

func (m *InventoryCategorySaveData) GetBaseCategoryDefinitionHash() uint32 {
	if m != nil && m.BaseCategoryDefinitionHash != nil {
		return *m.BaseCategoryDefinitionHash
	}
	return 0
}

func (m *InventoryCategorySaveData) GetQuantity() int32 {
	if m != nil && m.Quantity != nil {
		return *m.Quantity
	}
	return 0
}

type OakSDUSaveGameData struct {
	SduLevel             *int32   `protobuf:"varint,1,opt,name=sdu_level,json=sduLevel" json:"sdu_level,omitempty"`
	SduDataPath          *string  `protobuf:"bytes,2,opt,name=sdu_data_path,json=sduDataPath" json:"sdu_data_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OakSDUSaveGameData) Reset()         { *m = OakSDUSaveGameData{} }
func (m *OakSDUSaveGameData) String() string { return proto.CompactTextString(m) }
func (*OakSDUSaveGameData) ProtoMessage()    {}
func (*OakSDUSaveGameData) Descriptor() ([]byte, []int) {
	return fileDescriptor_24942b0aee0bf7ae, []int{3}
}

func (m *OakSDUSaveGameData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OakSDUSaveGameData.Unmarshal(m, b)
}
func (m *OakSDUSaveGameData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OakSDUSaveGameData.Marshal(b, m, deterministic)
}
func (m *OakSDUSaveGameData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OakSDUSaveGameData.Merge(m, src)
}
func (m *OakSDUSaveGameData) XXX_Size() int {
	return xxx_messageInfo_OakSDUSaveGameData.Size(m)
}
func (m *OakSDUSaveGameData) XXX_DiscardUnknown() {
	xxx_messageInfo_OakSDUSaveGameData.DiscardUnknown(m)
}

var xxx_messageInfo_OakSDUSaveGameData proto.InternalMessageInfo

func (m *OakSDUSaveGameData) GetSduLevel() int32 {
	if m != nil && m.SduLevel != nil {
		return *m.SduLevel
	}
	return 0
}

func (m *OakSDUSaveGameData) GetSduDataPath() string {
	if m != nil && m.SduDataPath != nil {
		return *m.SduDataPath
	}
	return ""
}

type RegisteredDownloadableEntitlement struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Consumed             *uint32  `protobuf:"varint,2,opt,name=consumed" json:"consumed,omitempty"`
	Registered           *bool    `protobuf:"varint,3,opt,name=registered" json:"registered,omitempty"`
	Seen                 *bool    `protobuf:"varint,4,opt,name=seen" json:"seen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisteredDownloadableEntitlement) Reset()         { *m = RegisteredDownloadableEntitlement{} }
func (m *RegisteredDownloadableEntitlement) String() string { return proto.CompactTextString(m) }
func (*RegisteredDownloadableEntitlement) ProtoMessage()    {}
func (*RegisteredDownloadableEntitlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_24942b0aee0bf7ae, []int{4}
}

func (m *RegisteredDownloadableEntitlement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredDownloadableEntitlement.Unmarshal(m, b)
}
func (m *RegisteredDownloadableEntitlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredDownloadableEntitlement.Marshal(b, m, deterministic)
}
func (m *RegisteredDownloadableEntitlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredDownloadableEntitlement.Merge(m, src)
}
func (m *RegisteredDownloadableEntitlement) XXX_Size() int {
	return xxx_messageInfo_RegisteredDownloadableEntitlement.Size(m)
}
func (m *RegisteredDownloadableEntitlement) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredDownloadableEntitlement.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredDownloadableEntitlement proto.InternalMessageInfo

func (m *RegisteredDownloadableEntitlement) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RegisteredDownloadableEntitlement) GetConsumed() uint32 {
	if m != nil && m.Consumed != nil {
		return *m.Consumed
	}
	return 0
}

func (m *RegisteredDownloadableEntitlement) GetRegistered() bool {
	if m != nil && m.Registered != nil {
		return *m.Registered
	}
	return false
}

func (m *RegisteredDownloadableEntitlement) GetSeen() bool {
	if m != nil && m.Seen != nil {
		return *m.Seen
	}
	return false
}

type RegisteredDownloadableEntitlements struct {
	EntitlementSourceAssetPath *string                              `protobuf:"bytes,1,opt,name=entitlement_source_asset_path,json=entitlementSourceAssetPath" json:"entitlement_source_asset_path,omitempty"`
	EntitlementIds             []int64                              `protobuf:"varint,2,rep,name=entitlement_ids,json=entitlementIds" json:"entitlement_ids,omitempty"`
	Entitlements               []*RegisteredDownloadableEntitlement `protobuf:"bytes,3,rep,name=entitlements" json:"entitlements,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                             `json:"-"`
	XXX_unrecognized           []byte                               `json:"-"`
	XXX_sizecache              int32                                `json:"-"`
}

func (m *RegisteredDownloadableEntitlements) Reset()         { *m = RegisteredDownloadableEntitlements{} }
func (m *RegisteredDownloadableEntitlements) String() string { return proto.CompactTextString(m) }
func (*RegisteredDownloadableEntitlements) ProtoMessage()    {}
func (*RegisteredDownloadableEntitlements) Descriptor() ([]byte, []int) {
	return fileDescriptor_24942b0aee0bf7ae, []int{5}
}

func (m *RegisteredDownloadableEntitlements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredDownloadableEntitlements.Unmarshal(m, b)
}
func (m *RegisteredDownloadableEntitlements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredDownloadableEntitlements.Marshal(b, m, deterministic)
}
func (m *RegisteredDownloadableEntitlements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredDownloadableEntitlements.Merge(m, src)
}
func (m *RegisteredDownloadableEntitlements) XXX_Size() int {
	return xxx_messageInfo_RegisteredDownloadableEntitlements.Size(m)
}
func (m *RegisteredDownloadableEntitlements) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredDownloadableEntitlements.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredDownloadableEntitlements proto.InternalMessageInfo

func (m *RegisteredDownloadableEntitlements) GetEntitlementSourceAssetPath() string {
	if m != nil && m.EntitlementSourceAssetPath != nil {
		return *m.EntitlementSourceAssetPath
	}
	return ""
}

func (m *RegisteredDownloadableEntitlements) GetEntitlementIds() []int64 {
	if m != nil {
		return m.EntitlementIds
	}
	return nil
}

func (m *RegisteredDownloadableEntitlements) GetEntitlements() []*RegisteredDownloadableEntitlement {
	if m != nil {
		return m.Entitlements
	}
	return nil
}

func init() {
	proto.RegisterType((*Vec3)(nil), "OakSave.Vec3")
	proto.RegisterType((*GameStatSaveGameData)(nil), "OakSave.GameStatSaveGameData")
	proto.RegisterType((*InventoryCategorySaveData)(nil), "OakSave.InventoryCategorySaveData")
	proto.RegisterType((*OakSDUSaveGameData)(nil), "OakSave.OakSDUSaveGameData")
	proto.RegisterType((*RegisteredDownloadableEntitlement)(nil), "OakSave.RegisteredDownloadableEntitlement")
	proto.RegisterType((*RegisteredDownloadableEntitlements)(nil), "OakSave.RegisteredDownloadableEntitlements")
}

func init() {
	proto.RegisterFile("OakShared.proto", fileDescriptor_24942b0aee0bf7ae)
}

var fileDescriptor_24942b0aee0bf7ae = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0xd5, 0x26, 0xa9, 0x48, 0xa7, 0x4d, 0x2b, 0x59, 0x1c, 0x96, 0xa0, 0xa2, 0xb0, 0x97, 0x06,
	0x24, 0x92, 0xd2, 0x1e, 0x38, 0x17, 0x82, 0xa0, 0x12, 0x02, 0xe4, 0xa8, 0x3d, 0x70, 0x59, 0x4d,
	0xd6, 0xd3, 0xac, 0xc5, 0xc6, 0x0e, 0x6b, 0x6f, 0x68, 0x72, 0xe5, 0x47, 0xf9, 0x14, 0x34, 0xce,
	0x92, 0x6e, 0x4f, 0xbd, 0xf9, 0xbd, 0x79, 0xf3, 0x3c, 0xcf, 0x63, 0x38, 0xfe, 0x86, 0x3f, 0xa7,
	0x39, 0x96, 0xa4, 0x46, 0xcb, 0xd2, 0x7a, 0x2b, 0x9e, 0x30, 0x81, 0x2b, 0x4a, 0xce, 0xa0, 0x73,
	0x43, 0xd9, 0x85, 0x38, 0x84, 0xe8, 0x2e, 0x8e, 0x06, 0xd1, 0xb0, 0x25, 0xa3, 0x3b, 0x46, 0xeb,
	0xb8, 0xb5, 0x45, 0x6b, 0x46, 0x9b, 0xb8, 0xbd, 0x45, 0x9b, 0x44, 0xc2, 0xd3, 0x4f, 0xb8, 0xa0,
	0xa9, 0x47, 0xcf, 0x0e, 0x7c, 0x9e, 0xa0, 0x47, 0x71, 0x02, 0xe0, 0x3c, 0xfa, 0x74, 0x85, 0x45,
	0x45, 0xc1, 0x6a, 0x4f, 0xee, 0x33, 0x73, 0xc3, 0x84, 0x78, 0x0e, 0x01, 0xa4, 0x4b, 0xf4, 0x79,
	0xb0, 0xde, 0x97, 0x5d, 0x26, 0xbe, 0xa3, 0xcf, 0x93, 0x0d, 0x3c, 0xbb, 0x32, 0x2b, 0x32, 0xde,
	0x96, 0xeb, 0x0f, 0xe8, 0x69, 0x6e, 0xcb, 0x35, 0x9b, 0x07, 0xe3, 0x4b, 0x38, 0x99, 0xa1, 0xa3,
	0x34, 0xab, 0x0b, 0xa9, 0xa2, 0x5b, 0x6d, 0xb4, 0xd7, 0xd6, 0xa4, 0x39, 0xba, 0x3c, 0xdc, 0xd5,
	0x93, 0x7d, 0x16, 0xfd, 0x6f, 0x9e, 0xec, 0x24, 0x9f, 0xd1, 0xe5, 0xa2, 0x0f, 0xdd, 0x5f, 0x15,
	0x1a, 0xaf, 0xfd, 0x36, 0xd6, 0x9e, 0xdc, 0xe1, 0xe4, 0x1a, 0x04, 0x3f, 0xc6, 0xe4, 0xfa, 0x41,
	0x1a, 0x1e, 0x57, 0x55, 0x69, 0x41, 0x2b, 0x2a, 0xea, 0x30, 0x5d, 0xa7, 0xaa, 0x2f, 0x8c, 0x45,
	0x02, 0x3d, 0x2e, 0x2a, 0xf4, 0xd8, 0xcc, 0x73, 0xe0, 0x54, 0xc5, 0xcd, 0x21, 0xd2, 0x9f, 0x08,
	0x5e, 0x4a, 0x9a, 0x6b, 0xe7, 0xa9, 0x24, 0x35, 0xb1, 0xbf, 0x4d, 0x61, 0x51, 0xe1, 0xac, 0xa0,
	0x8f, 0x7c, 0x6f, 0x41, 0x0b, 0x32, 0x5e, 0x1c, 0x41, 0x4b, 0xab, 0xda, 0xbf, 0xa5, 0x15, 0x0f,
	0x9a, 0x59, 0xe3, 0xaa, 0x05, 0xa9, 0x60, 0xda, 0x93, 0x3b, 0x2c, 0x5e, 0x00, 0x94, 0x3b, 0xc3,
	0xb0, 0x8f, 0xae, 0x6c, 0x30, 0x42, 0x40, 0xc7, 0x11, 0x99, 0xb8, 0x13, 0x2a, 0xe1, 0x9c, 0xfc,
	0x8d, 0x20, 0x79, 0x74, 0x0a, 0xc7, 0x4f, 0x4c, 0xf7, 0x38, 0x75, 0xb6, 0x2a, 0x33, 0x4a, 0xd1,
	0x39, 0xaa, 0x17, 0x16, 0x85, 0x80, 0xfd, 0x86, 0x68, 0x1a, 0x34, 0x97, 0x2c, 0xe1, 0xbc, 0xe2,
	0x14, 0x8e, 0x9b, 0x16, 0x5a, 0xb9, 0xb8, 0x35, 0x68, 0x0f, 0xdb, 0xf2, 0xa8, 0x41, 0x5f, 0x29,
	0x27, 0xbe, 0xc2, 0x61, 0x83, 0x71, 0x71, 0x7b, 0xd0, 0x1e, 0x1e, 0x9c, 0xbf, 0x1e, 0xd5, 0x3f,
	0x72, 0xf4, 0xe8, 0xb8, 0xf2, 0x41, 0xff, 0xfb, 0x57, 0x3f, 0x4e, 0xe7, 0xda, 0xe7, 0xd5, 0x6c,
	0x94, 0xd9, 0xc5, 0x38, 0xbb, 0xd5, 0xe7, 0x67, 0x6f, 0xdf, 0x8d, 0x67, 0xc5, 0xc5, 0x1b, 0x87,
	0x2b, 0x1a, 0x6b, 0xe3, 0xa9, 0x34, 0x58, 0x8c, 0x97, 0xb3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xc9, 0x17, 0x32, 0x6b, 0x07, 0x03, 0x00, 0x00,
}
